builds:
  - main: main.go
    binary: trello
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -X github.com/mikutas/trello/cmd.version={{.Version}}
archives:
  - format: binary
